name: Build & Test

on: [push, pull_request]

permissions:
  packages: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - run: npm i

    - name: Run tests
      run: npm test

  build_branch:
    needs: test
  
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          context: .
          tags: ghcr.io/elanis/tp1-react:${{ github.head_ref || github.ref_name }}  
